version: "3"
services:
  backend:
    build: ./back/
    container_name: lectopt-back
    env_file: .env
    restart: always
    volumes:
      - ./back:/lectopt/back
    ports:
      - "8080:8080"
    tty: true

  frontend:
    build: ./frontend/
    container_name: lectopt-front
    ports:
      - "3000:3000"
    volumes:
      - .:/lectopt/front